- Chart.yaml
- README.md
- templates/_helpers.tpl
- templates/statefullset.yaml
- templates/svc-headless.yaml
- values.yaml
This is a cleanup, update and fix patch. To ensure all features actually work.
(newsflash: In a lot of cases replication isn't working very well)
As there are replication fixes in v1.4.0 of the container, I updated and tested the new container.
I also patched the bug currently causing many of us not to be able to use replication. The host list for replication NEEDS the **FULL** fqdn. So I added a field to set the cluster name and changed the template to ensure we generate the complete fqdn for creating the replication host list.
I also ported the recently added feature to set the loglevel from upstream, added an actually working installation guide to the readme.
TLDR: This should prevent the FLOOD of replication issues that plaguing this build and are being filed in both the container and …
> Update container, Fix replication, port log-level and update readme

- templates/statefullset.yaml
This mounts the custom-ldif files under /container/service/slapd/assets/config/bootstrap/ldif/custom so that they're loaded automatically on openldap startup
> added custom-ldif configmap mount

- Chart.yaml
- README.md
- templates/statefullset.yaml
- values.yaml
- StatefulSets do not have `strategy` parameter, instead there is `updateStrategy` one for that purposes.
- No need to override/unset default imagePullSecrets anymore (useful when pull secret is provided in the namespace)
> Fix StatefulSet update strategy

- templates/statefullset.yaml
First of all I want to thank you very much for this Helm chart of OpenLDAP. I'm using it for a long time now and it's working great :+1: 
However I noticed that the `podAntiAffinity` was not working correctly, and I found out that it tries to match to wrong labels instead of the ones actually used in Line 34-35.
Trying to get that functionality back with this PR :)
> Fix pod anti affinity using wrong labels

- README.md
- templates/statefullset.yaml
- values.yaml
This PR adds two new features:
1.  Liveness and readiness probes are now customizable with respect to timing and thresholds and they can be disabled.
2. A startup probe is added as an option (disabled by default).
The reason for this PR is to allow adjustments in environments where it takes longer than 2 minutes for the initial startup (or any other requirements around timing of probes and thresholds). Sometimes the DH param generation takes longer than the `initialDelaySeconds + periodSeconds * failureThreshold` putting the pod into a crash loop.
This also allows the liveness probe to be easily disabled when debugging a startup error to prevent pod restarts.
This is a new capability, but it is functionally identical to the existing behavior in the default setting.
> Add startup probe and allow probe modification

- values.yaml
Makes the usage a little simpler without backtracking it to secrets.yml
- move existingSecret to adminPassword / configPassword since they logically go together and are mutually exclusive
- add docs to adminPassword / configPassword that they are ignored if existingSecret if used
> Add hint which secret key is expected for existingSecret + minor docs

- README.md
- templates/pod-disruption-budget.yaml
- values.yaml
OpenLDAP clusters with multiple replicas should ask cluster operators to not shut all replicas at once (e.g. during Node Pool upgrades). A Pod Disruption Budget should be provided by the helm chart, for easy and consistent selector settings.
This change is backwards compatible with possible pre-existing PDBs and workflows allowing complete shutdown of clusters, as the flag to emit a PDB definition defaults to `false`.
Without this change, cluster owners are forced to create a PDB by themselves, manually managing the selector.
> Add Pod Disruption Budget for Stateful Set

- README.md
- templates/_helpers.tpl
- templates/configmap-customschema.yaml
- templates/configmap-env.yaml
- templates/statefulset.yaml
- values.yaml
Solves following feature request from the Readme:
```
- Replication is now purely setup by configuration. Extra schemas are loaded using `LDAP_EXTRA_SCHEMAS: "cosine,inetorgperson,nis,syncprov,serverid,csyncprov,rep,bsyncprov,brep,acls".
- For now this list is harcoded and will be configurable in a future update.
- (let me know if you need this feature priorityzed)
```
It now allows you to set custom schemas in `customSchemaFiles` like you can do with `customLdifFiles` for LDIF files.
Sadly I found no way to support a `customSchemaCm` analogous to `customLdifCm` (because of the subPath mount logic in statefulset.yaml).
> add customSchemaFiles option

- .bin/myval.yaml
- .bin/singleNode.yaml
- .bin/user.ldif
- .github/workflows/ci.yml
- test.yaml
improve CI by 
- Write into openldap
- Check the number of item returned
- Deploy openldap in single node
> Improve ci

- README.md
- templates/statefulset.yaml
"podAnnotations" parameter is defined in values.yaml file but not used in the actual statefulset/pod template. Therefore it is impossible to add additional pod annotation to the openldap pods currently. This PR fixes the issue.
> Fix: Add extra pod annotation to the statefulset template

- templates/statefulset.yaml
Previously the init container only copied tls.crt to ca.crt after generating a new certificate. When using cert-manager with an ACME issuer to generate a certificate, the resulting secret will also not have a ca.crt. When doing the copy like this, both cases would be covered without impacting other cases.
> Copy tls.crt to ca.crt always unless ca.crt exists

- .bin/myval.yaml
- Chart.yaml
- README.md
- templates/_helpers.tpl
- templates/statefulset.yaml
- values.yaml
Fix issues 130 and 131
enable containersecuritycontext and resources limit for initcontainers
> Fix issues 130 and 131

- templates/_helpers.tpl
- values.yaml
Custom schema filenames are inserted into LDAP_EXTRA_SCHEMAS in an unsorted fashion, causing inconsistencies every time a new schema is added, or even in a different version of the helm. This commit enable customSchemaFiles keys sorting, allowing control over the loading sequence and using dependent custom schemas.
> feat(helpers): sort schema apply sequence

- .bin/disableLdapPort.yaml
- .bin/simpleUser.ldif
- .github/workflows/ci.yml
- Chart.yaml
- README.md
- templates/service.yaml
- templates/svc-headless.yaml
- values.yaml
When using service as load balancer, if we setup ldap to be on secure port only we don't want to expose the insecure port. Currently there is no way to do that.
With this modification, users can enable or disable exposition of insecure or secure port on the service.
Default values keep the current behaviour.
> Allow to disable port on services.

- Chart.yaml
- templates/statefulset.yaml
> add acls setup for all replicas during the first startup

- Chart.yaml
- templates/_helpers.tpl
Allow user to use short domain name for the `LDAP_ROOT` e.g : `o=domain` or `example` which will be  translated to `dc=example`
> add support for short domain 'o=toto'

- README.md
- templates/service.yaml
- values.yaml
Allows a user to define a static IP for the service when the service type is clusterIP
Fix #168
> Add possibility to define static clusterIp for service

- templates/configmap-env.yaml
Previously breaking with msg: chart openldap-stack-ha@4.2.2: YAML parse error on openldap-stack-ha/templates/configmap-env.yaml: error converting YAML to JSON: yaml: line 20: found character that cannot start any token
See https://stackoverflow.com/a/22235064/1484823 for special characters requiring quotes
> Quote LDAP_PASSWORDS that may begin with special characters

- README.md
- templates/service.yaml
- values.yaml
Deployments function well in a dual-stack configuration, yet there seems to be no method to configure the ipFamilyPolicy as either "PreferDualStack" or "RequireDualStack."
> Support ipFamilyPolicy

- README.md
- templates/_helpers.tpl
- values.yaml
Enable the configuration of the Certificate Authority for replication to validate certificates signed by a custom root certificate.
> Enable setting the CA for replication.

- templates/_helpers.tpl
There's a typo in the _helpers.tpl when setting tls_reqcert value. The **tls_cacert** is used instead of  **tls_reqcert** which results in the following config:
```
olcSyncrepl: {0}rid=101 provider=ldap://ldap-0.ldap-headless.openldap.svc.clus
ter.local:1389 binddn=xxx bindmethod=simple credentials
=xxxx searchbase=o=xxx type=refreshAndPersist interval=00:00:00:10 net
work-timeout=0 retry="60 +" timeout=1 starttls=critical tls_cacert=never tls_
cacert=/opt/bitnami/openldap/certs/ca.crt
```
setting **tls_cacert=never** and leaving out  **tls_reqcert** completely
> Fix cacert --> reqcert typo

- README.md
- templates/service-readonly.yaml
- templates/service.yaml
- values.yaml
This adds support for the externalTrafficPolicy setting for the service resources. Setting externalTrafficPolicy to local preserves the client ip for the pod (https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip)
I don't think this fixes any open issues, but it resolves an issue I have this helm chart (Client IPs are not preserved for purposes of logging device accessing ldap through the loadbalancer service)
* [ X ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ X ] Have you updated the readme?
* [ X ] Is this PR backward compatible? **If it is not backward compatible, please discuss open a ticket first**
> add support for externalTrafficPolicy on service
